{{ config (materialized = "table") }}
SELECT
    SHIPMENT_ID,
    ORDER_ID,
    WAREHOUSE_ID,
    SHIPPED_DATE,
    DELIVERY_DATE,
    CARRIER,
    STATUS,
    CREATED_DATE,
    MODIFIED_DATE
FROM
    {{ source('raw', 'RAW_SHIPMENTS') }} a
WHERE CREATED_DATE >= CURRENT_DATE() OR MODIFIED_DATE >= CURRENT_DATE()


